heat_template_version: 2014-10-16
description: Loadbalanced Deis cluster
parameters:
  image:
    type: string
    default: CoreOS-647.2.0
    description: CoreOS Image Name
  key:
    type: string
    default: deis-key
    description: Name of Key Pair for instances
  flavor:
    type: string
    default: m1.large
    description: Name of Flavor for instances
  size:
    type: number
    default: 3
    description: Number of instances
  external_network:
    type: string
    default: external
    description: UUID or Name of external network
  http_floating_ip:
    type: string
    description: Floating IP address to use for http load balancer
  network:
    type: string
    default: deis-network
    description: UUID or Name of private network
  subnet:
    type: string
    default: deis-subnet
    description: UUID or Name of private subnet
  http_port:
    type: number
    default: 80
  git_ssh_port:
    type: number
    default: 2222

resources:
  deis_cluster:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: size}
      resource_def:
        type: lb_server.yaml
        properties:
          image: {get_param: image}
          key_name: {get_param: key}
          flavor: {get_param: flavor}
          external_network: {get_param: external_network}
          network: {get_param: network}
          subnet: {get_param: subnet}
          http_port: {get_param: http_port}
          http_pool_id: {get_resource: http_pool}
          git_ssh_port: {get_param: git_ssh_port}
          git_ssh_pool_id: {get_resource: git_ssh_pool}
          user_data: {get_file: ../coreos/user-data}
  http_monitor:
    type: OS::Neutron::HealthMonitor
    properties:
      type: HTTP
      delay: 5
      max_retries: 5
      timeout: 5
      url_path: /health-check
  http_pool:
    type: OS::Neutron::Pool
    properties:
      protocol: HTTP
      monitors: [{get_resource: http_monitor}]
      subnet: {get_param: subnet}
      lb_method: ROUND_ROBIN
      vip:
        protocol_port: {get_param: http_port}
  http_lb:
    type: OS::Neutron::LoadBalancer
    properties:
      protocol_port: {get_param: http_port}
      pool_id: {get_resource: http_pool}
  http_lb_floating:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: external_network}
      floating_ip_address: {get_param: http_floating_ip}
      port_id: {get_attr: [http_pool, vip, port_id]}
  git_ssh_monitor:
    type: OS::Neutron::HealthMonitor
    properties:
      type: TCP
      delay: 5
      max_retries: 5
      timeout: 5
  git_ssh_pool:
    type: OS::Neutron::Pool
    properties:
      protocol: TCP
      monitors: [{get_resource: git_ssh_monitor}]
      subnet: {get_param: subnet}
      lb_method: ROUND_ROBIN
      vip:
        protocol_port: {get_param: git_ssh_port}
  git_ssh_lb:
    type: OS::Neutron::LoadBalancer
    properties:
      protocol_port: {get_param: git_ssh_port}
      pool_id: {get_resource: git_ssh_pool}
  git_ssh_lb_floating:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: external_network}
      port_id: {get_attr: [git_ssh_pool, vip, port_id]}

outputs:
  http_lb_ip:
    description: The IP address of the load balancer
    value: {get_attr: [http_lb_floating, floating_ip_address]}
  git_ssh_lb_ip:
    description: The IP address of the load balancer
    value: {get_attr: [git_ssh_lb_floating, floating_ip_address]}
  deis_cluster_floating_ips:
    description: The IP addresses of the cluster members
    value: {get_attr: [deis_cluster, server_floating_ip]}
